# Generated by Django 4.1.5 on 2023-02-18 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0004_alter_mark_reyting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching.academy')),
            ],
        ),
    ]
